# ~/.GH/Qompass/Templates/qtemplate/.github/workflows/zenodo.yml
# --------------------------------------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

name: Sync Zenodo Metadata

on:
  workflow_dispatch:
  push:
    paths:
      - '.zenodo.json'
      - 'CITATION.cff'
      - 'citation.bib'

jobs:
  sync-metadata:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Zenodo sync script
        env:
          PATH: "$HOME/.local/bin:$PATH"
          run: |
            zs || ~/.local/bin/zs
